const std = @import("std");
const sqlite = @import("sqlite");
const db_schema = @import("schema.zig");
const models = @import("models.zig");
const helpers = @import("helpers.zig");
const connection = @import("connection.zig");
const auth_repository = @import("repositories/auth.zig");
const nob_repository = @import("repositories/nob.zig");
const browser_run_repository = @import("repositories/browser_run.zig");
const nob_model = @import("../nob/model.zig");

pub const Db = connection.Db;
pub const DbError = models.DbError;
pub const SnapshotSummary = models.SnapshotSummary;
pub const SnapshotSummaries = models.SnapshotSummaries;
pub const Observation = models.Observation;
pub const NameValueRow = models.NameValueRow;
pub const NameValueRows = models.NameValueRows;
pub const InventoryFilter = models.InventoryFilter;
pub const InventoryItem = models.InventoryItem;
pub const InventoryItems = models.InventoryItems;
pub const InventoryFacet = models.InventoryFacet;
pub const InventoryFacets = models.InventoryFacets;
pub const ProjectDetails = models.ProjectDetails;
pub const ProjectCorrelation = models.ProjectCorrelation;
pub const ProjectCorrelations = models.ProjectCorrelations;
pub const TopologyRow = models.TopologyRow;
pub const TopologyRows = models.TopologyRows;
pub const SecretScanSurface = models.SecretScanSurface;
pub const secret_scan_surfaces = models.secret_scan_surfaces;
pub const MetricRow = models.MetricRow;
pub const MetricRows = models.MetricRows;
pub const CloudflareAccountRow = models.CloudflareAccountRow;
pub const CloudflareAccountRows = models.CloudflareAccountRows;
pub const CloudflareZoneRow = models.CloudflareZoneRow;
pub const CloudflareZoneRows = models.CloudflareZoneRows;
pub const CloudflareDnsRecordRow = models.CloudflareDnsRecordRow;
pub const CloudflareDnsRecordRows = models.CloudflareDnsRecordRows;
pub const ContainerRow = models.ContainerRow;
pub const ContainerRows = models.ContainerRows;
pub const CloudflareKindCount = models.CloudflareKindCount;
pub const CloudflareKindCounts = models.CloudflareKindCounts;
pub const CloudflareResourceHintRow = models.CloudflareResourceHintRow;
pub const CloudflareResourceHintRows = models.CloudflareResourceHintRows;
pub const CloudflareInventoryHintRow = models.CloudflareInventoryHintRow;
pub const CloudflareInventoryHintRows = models.CloudflareInventoryHintRows;
pub const HostingerVpsRow = models.HostingerVpsRow;
pub const HostingerVpsRows = models.HostingerVpsRows;
pub const HostingerResourceHintRow = models.HostingerResourceHintRow;
pub const HostingerResourceHintRows = models.HostingerResourceHintRows;
pub const HostingerInventoryHintRow = models.HostingerInventoryHintRow;
pub const HostingerInventoryHintRows = models.HostingerInventoryHintRows;
pub const HostingerKindCount = models.HostingerKindCount;
pub const HostingerKindCounts = models.HostingerKindCounts;
pub const HostingerMetricSummary = models.HostingerMetricSummary;
pub const HostingerMetricSummaries = models.HostingerMetricSummaries;
pub const HostingerVpsFamilySummary = models.HostingerVpsFamilySummary;
pub const HostingerVpsFamilySummaries = models.HostingerVpsFamilySummaries;
pub const AuditEvent = models.AuditEvent;
pub const AuditEvents = models.AuditEvents;
pub const ProviderEvidenceFilter = models.ProviderEvidenceFilter;
pub const ProviderEvidenceEvent = models.ProviderEvidenceEvent;
pub const ProviderEvidenceEvents = models.ProviderEvidenceEvents;
pub const ProviderEvidenceSummaryRow = models.ProviderEvidenceSummaryRow;
pub const ProviderEvidenceSummaryRows = models.ProviderEvidenceSummaryRows;
pub const RouteCaptureEvidenceFilter = models.RouteCaptureEvidenceFilter;
pub const RouteCaptureEvidenceRow = models.RouteCaptureEvidenceRow;
pub const RouteCaptureEvidenceRows = models.RouteCaptureEvidenceRows;
pub const RouteSourceEvidenceRow = models.RouteSourceEvidenceRow;
pub const RouteSourceEvidenceRows = models.RouteSourceEvidenceRows;
pub const columnText = helpers.columnText;
pub const AuthCredential = auth_repository.Credential;
pub const NobProject = nob_model.Project;
pub const NobProjects = nob_model.Projects;
pub const NobResource = nob_model.Resource;
pub const NobResources = nob_model.Resources;
pub const NobAction = nob_model.Action;
pub const NobActions = nob_model.Actions;
pub const NobDiscoveryState = nob_model.DiscoveryState;
pub const NobTrustState = nob_model.TrustState;
pub const NobRunnerState = nob_model.RunnerState;
pub const NobResourceDeclaration = nob_repository.ResourceDeclaration;
pub const NobActionDeclaration = nob_repository.ActionDeclaration;
pub const NobActionAvailability = nob_repository.ActionAvailability;
pub const NobResourceObservation = nob_repository.ResourceObservation;
pub const NobPlan = nob_model.Plan;
pub const NobRun = nob_model.Run;
pub const NobRuns = nob_model.Runs;
pub const NobRunEvent = nob_model.RunEvent;
pub const NobRunEvents = nob_model.RunEvents;
pub const NobBrokerAuthorization = nob_repository.BrokerAuthorization;
pub const NobArtifacts = nob_model.Artifacts;
pub const NobManagedUnit = nob_repository.ManagedUnit;
pub const NobSecretBinding = nob_model.SecretBinding;
pub const BrowserRun = browser_run_repository.Run;
pub const BrowserRuns = browser_run_repository.Runs;

test "sqlite schema initializes" {
    const allocator = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const db_path = try std.fmt.allocPrint(allocator, ".zig-cache/tmp/{s}/cloudio-store.db", .{tmp.sub_path});
    defer allocator.free(db_path);
    var db = try Db.open(std.testing.io, db_path);
    defer db.close();
    try db.initSchema();
    try std.testing.expectEqual(db_schema.latest_version, try db.schemaVersion());
    try std.testing.expectEqual(@as(i64, 0), try db.countTable("snapshots"));
}

